version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  app:
    container_name: django
    build: ./django
    command: uwsgi --socket :8001 --module mysite.wsgi --py-autoreload 1 --logto /tmp/mylog.log --processes 12
    expose:
      - "8001"
    volumes:
      - ./django:/code
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - app